# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.80.4 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: .template\.yaml$
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.5.4"
    hooks:
      - id: checkov
        verbose: true
        args: [--soft-fail]
