name: Preview

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      stack-name:
        description: The deployed stack name
        value: ${{ jobs.deploy.outputs.stack-name }}
      aws-region:
        description: The region in which the stack was deployed
        value: ${{ jobs.deploy.outputs.aws-region }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build SAM app
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Build SAM application
        uses: govuk-one-login/github-actions/sam/build-application@6023e6872503eec9c057061eba23bddf7f445d9f
        id: build
        with:
          template: infrastructure/template.yaml
          cache-key: cri-toy-api
          pull-repository: true

  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    concurrency:
      group: deploy-development-${{ github.head_ref || github.ref_name }}
    environment:
      name: development
      url: ${{ steps.deploy.outputs.stack-url }}
    outputs:
      aws-region: ${{ steps.deploy.outputs.aws-region }}
      stack-name: ${{ steps.deploy.outputs.stack-name }}
    steps:
      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@6023e6872503eec9c057061eba23bddf7f445d9f
        id: deploy
        with:
          sam-deployment-bucket: ${{ vars.DEPLOYMENT_ARTIFACTS_BUCKET }}
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          stack-name-prefix: preview-cri-toy-api
          stack-name-length-limit: 50
          cache-key: cri-toy-api
          s3-prefix: preview
          pull-repository: true
          delete-failed-stack: true
          tags: |
            cri:component=ipv-cri-toy-api
            cri:stack-type=preview
            cri:application=Orange
            cri:deployment-source=github-actions
          parameters: |
            Environment=dev
