name: Deploy to Dev

on:
  workflow_dispatch: # deploy manually
  push:
    branches: [main]

concurrency:
  group: deploy-dev
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.74.0

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/template.yaml

      - name: SAM build
        run: |
          mkdir out
          sam build -t infrastructure/template.yaml -b out/

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.8
        with:
          artifact-bucket-name: ${{ secrets.DEV_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
          working-directory: ./out
