name: SonarCloud

on:
  workflow_call:
    secrets:
      github-token: { required: true }
      sonar-token: { required: true }

concurrency:
  group: sonarcloud-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  scan:
    name: SonarCloud
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get coverage results
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage

      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
